// Code generated by go-swagger; DO NOT EDIT.

package external_system_sailplane_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemSailplaneFlightsGetReader is a Reader for the ExternalSystemSailplaneFlightsGet structure.
type ExternalSystemSailplaneFlightsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSailplaneFlightsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSailplaneFlightsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/pel/public/externalsystemsailplaneflights/{id}] ExternalSystemSailplaneFlights_Get", response, response.Code())
	}
}

// NewExternalSystemSailplaneFlightsGetOK creates a ExternalSystemSailplaneFlightsGetOK with default headers values
func NewExternalSystemSailplaneFlightsGetOK() *ExternalSystemSailplaneFlightsGetOK {
	return &ExternalSystemSailplaneFlightsGetOK{}
}

/*
ExternalSystemSailplaneFlightsGetOK describes a response with status code 200, with default header values.

ExternalSystemSailplaneFlightsGetOK external system sailplane flights get o k
*/
type ExternalSystemSailplaneFlightsGetOK struct {
	Payload *models.ExternalSystemSailplaneFlightOutput
}

// IsSuccess returns true when this external system sailplane flights get o k response has a 2xx status code
func (o *ExternalSystemSailplaneFlightsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this external system sailplane flights get o k response has a 3xx status code
func (o *ExternalSystemSailplaneFlightsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this external system sailplane flights get o k response has a 4xx status code
func (o *ExternalSystemSailplaneFlightsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this external system sailplane flights get o k response has a 5xx status code
func (o *ExternalSystemSailplaneFlightsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this external system sailplane flights get o k response a status code equal to that given
func (o *ExternalSystemSailplaneFlightsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the external system sailplane flights get o k response
func (o *ExternalSystemSailplaneFlightsGetOK) Code() int {
	return 200
}

func (o *ExternalSystemSailplaneFlightsGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pel/public/externalsystemsailplaneflights/{id}][%d] externalSystemSailplaneFlightsGetOK %s", 200, payload)
}

func (o *ExternalSystemSailplaneFlightsGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pel/public/externalsystemsailplaneflights/{id}][%d] externalSystemSailplaneFlightsGetOK %s", 200, payload)
}

func (o *ExternalSystemSailplaneFlightsGetOK) GetPayload() *models.ExternalSystemSailplaneFlightOutput {
	return o.Payload
}

func (o *ExternalSystemSailplaneFlightsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemSailplaneFlightOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
