// Code generated by go-swagger; DO NOT EDIT.

package external_system_sailplane_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new external system sailplane flights API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new external system sailplane flights API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new external system sailplane flights API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for external system sailplane flights API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ExternalSystemSailplaneFlightsDelete(params *ExternalSystemSailplaneFlightsDeleteParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*ExternalSystemSailplaneFlightsDeleteOK, error)

	ExternalSystemSailplaneFlightsGet(params *ExternalSystemSailplaneFlightsGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ExternalSystemSailplaneFlightsGetOK, error)

	ExternalSystemSailplaneFlightsPost(params *ExternalSystemSailplaneFlightsPostParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ExternalSystemSailplaneFlightsPostOK, error)

	ExternalSystemSailplaneFlightsPostMultiple(params *ExternalSystemSailplaneFlightsPostMultipleParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*ExternalSystemSailplaneFlightsPostMultipleOK, error)

	ExternalSystemSailplaneFlightsPut(params *ExternalSystemSailplaneFlightsPutParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ExternalSystemSailplaneFlightsPutOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ExternalSystemSailplaneFlightsDelete deletes an existing sailplane flight in capzlog aero
*/
func (a *Client) ExternalSystemSailplaneFlightsDelete(params *ExternalSystemSailplaneFlightsDeleteParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*ExternalSystemSailplaneFlightsDeleteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExternalSystemSailplaneFlightsDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ExternalSystemSailplaneFlights_Delete",
		Method:             "DELETE",
		PathPattern:        "/api/pel/public/externalsystemsailplaneflights/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ExternalSystemSailplaneFlightsDeleteReader{formats: a.formats, writer: writer},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExternalSystemSailplaneFlightsDeleteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ExternalSystemSailplaneFlights_Delete: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ExternalSystemSailplaneFlightsGet gets a sailplane flight from capzlog aero based on the external system unique ID
*/
func (a *Client) ExternalSystemSailplaneFlightsGet(params *ExternalSystemSailplaneFlightsGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ExternalSystemSailplaneFlightsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExternalSystemSailplaneFlightsGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ExternalSystemSailplaneFlights_Get",
		Method:             "GET",
		PathPattern:        "/api/pel/public/externalsystemsailplaneflights/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ExternalSystemSailplaneFlightsGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExternalSystemSailplaneFlightsGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ExternalSystemSailplaneFlights_Get: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ExternalSystemSailplaneFlightsPost creates a sailplane flight in capzlog aero
*/
func (a *Client) ExternalSystemSailplaneFlightsPost(params *ExternalSystemSailplaneFlightsPostParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ExternalSystemSailplaneFlightsPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExternalSystemSailplaneFlightsPostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ExternalSystemSailplaneFlights_Post",
		Method:             "POST",
		PathPattern:        "/api/pel/public/externalsystemsailplaneflights",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ExternalSystemSailplaneFlightsPostReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExternalSystemSailplaneFlightsPostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ExternalSystemSailplaneFlights_Post: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ExternalSystemSailplaneFlightsPostMultiple creates multiple sailplane flights in capzlog aero
*/
func (a *Client) ExternalSystemSailplaneFlightsPostMultiple(params *ExternalSystemSailplaneFlightsPostMultipleParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*ExternalSystemSailplaneFlightsPostMultipleOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExternalSystemSailplaneFlightsPostMultipleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ExternalSystemSailplaneFlights_PostMultiple",
		Method:             "POST",
		PathPattern:        "/api/pel/public/externalsystemsailplaneflights/PostMultiple",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ExternalSystemSailplaneFlightsPostMultipleReader{formats: a.formats, writer: writer},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExternalSystemSailplaneFlightsPostMultipleOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ExternalSystemSailplaneFlights_PostMultiple: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ExternalSystemSailplaneFlightsPut modifies an existing sailplane flight in capzlog aero
*/
func (a *Client) ExternalSystemSailplaneFlightsPut(params *ExternalSystemSailplaneFlightsPutParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ExternalSystemSailplaneFlightsPutOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExternalSystemSailplaneFlightsPutParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ExternalSystemSailplaneFlights_Put",
		Method:             "PUT",
		PathPattern:        "/api/pel/public/externalsystemsailplaneflights/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ExternalSystemSailplaneFlightsPutReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExternalSystemSailplaneFlightsPutOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ExternalSystemSailplaneFlights_Put: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
