// Code generated by go-swagger; DO NOT EDIT.

package external_system_sailplane_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// NewExternalSystemSailplaneFlightsPostMultipleParams creates a new ExternalSystemSailplaneFlightsPostMultipleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemSailplaneFlightsPostMultipleParams() *ExternalSystemSailplaneFlightsPostMultipleParams {
	return &ExternalSystemSailplaneFlightsPostMultipleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemSailplaneFlightsPostMultipleParamsWithTimeout creates a new ExternalSystemSailplaneFlightsPostMultipleParams object
// with the ability to set a timeout on a request.
func NewExternalSystemSailplaneFlightsPostMultipleParamsWithTimeout(timeout time.Duration) *ExternalSystemSailplaneFlightsPostMultipleParams {
	return &ExternalSystemSailplaneFlightsPostMultipleParams{
		timeout: timeout,
	}
}

// NewExternalSystemSailplaneFlightsPostMultipleParamsWithContext creates a new ExternalSystemSailplaneFlightsPostMultipleParams object
// with the ability to set a context for a request.
func NewExternalSystemSailplaneFlightsPostMultipleParamsWithContext(ctx context.Context) *ExternalSystemSailplaneFlightsPostMultipleParams {
	return &ExternalSystemSailplaneFlightsPostMultipleParams{
		Context: ctx,
	}
}

// NewExternalSystemSailplaneFlightsPostMultipleParamsWithHTTPClient creates a new ExternalSystemSailplaneFlightsPostMultipleParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemSailplaneFlightsPostMultipleParamsWithHTTPClient(client *http.Client) *ExternalSystemSailplaneFlightsPostMultipleParams {
	return &ExternalSystemSailplaneFlightsPostMultipleParams{
		HTTPClient: client,
	}
}

/*
ExternalSystemSailplaneFlightsPostMultipleParams contains all the parameters to send to the API endpoint

	for the external system sailplane flights post multiple operation.

	Typically these are written to a http.Request.
*/
type ExternalSystemSailplaneFlightsPostMultipleParams struct {

	/* InputEntities.

	   Sailplane flights to be created
	*/
	InputEntities []*models.ExternalSystemSailplaneFlightInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system sailplane flights post multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) WithDefaults() *ExternalSystemSailplaneFlightsPostMultipleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system sailplane flights post multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system sailplane flights post multiple params
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) WithTimeout(timeout time.Duration) *ExternalSystemSailplaneFlightsPostMultipleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system sailplane flights post multiple params
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system sailplane flights post multiple params
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) WithContext(ctx context.Context) *ExternalSystemSailplaneFlightsPostMultipleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system sailplane flights post multiple params
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system sailplane flights post multiple params
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) WithHTTPClient(client *http.Client) *ExternalSystemSailplaneFlightsPostMultipleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system sailplane flights post multiple params
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInputEntities adds the inputEntities to the external system sailplane flights post multiple params
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) WithInputEntities(inputEntities []*models.ExternalSystemSailplaneFlightInput) *ExternalSystemSailplaneFlightsPostMultipleParams {
	o.SetInputEntities(inputEntities)
	return o
}

// SetInputEntities adds the inputEntities to the external system sailplane flights post multiple params
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) SetInputEntities(inputEntities []*models.ExternalSystemSailplaneFlightInput) {
	o.InputEntities = inputEntities
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemSailplaneFlightsPostMultipleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.InputEntities != nil {
		if err := r.SetBodyParam(o.InputEntities); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
