// Code generated by go-swagger; DO NOT EDIT.

package external_system_sailplane_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// NewExternalSystemSailplaneFlightsPostParams creates a new ExternalSystemSailplaneFlightsPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemSailplaneFlightsPostParams() *ExternalSystemSailplaneFlightsPostParams {
	return &ExternalSystemSailplaneFlightsPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemSailplaneFlightsPostParamsWithTimeout creates a new ExternalSystemSailplaneFlightsPostParams object
// with the ability to set a timeout on a request.
func NewExternalSystemSailplaneFlightsPostParamsWithTimeout(timeout time.Duration) *ExternalSystemSailplaneFlightsPostParams {
	return &ExternalSystemSailplaneFlightsPostParams{
		timeout: timeout,
	}
}

// NewExternalSystemSailplaneFlightsPostParamsWithContext creates a new ExternalSystemSailplaneFlightsPostParams object
// with the ability to set a context for a request.
func NewExternalSystemSailplaneFlightsPostParamsWithContext(ctx context.Context) *ExternalSystemSailplaneFlightsPostParams {
	return &ExternalSystemSailplaneFlightsPostParams{
		Context: ctx,
	}
}

// NewExternalSystemSailplaneFlightsPostParamsWithHTTPClient creates a new ExternalSystemSailplaneFlightsPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemSailplaneFlightsPostParamsWithHTTPClient(client *http.Client) *ExternalSystemSailplaneFlightsPostParams {
	return &ExternalSystemSailplaneFlightsPostParams{
		HTTPClient: client,
	}
}

/*
ExternalSystemSailplaneFlightsPostParams contains all the parameters to send to the API endpoint

	for the external system sailplane flights post operation.

	Typically these are written to a http.Request.
*/
type ExternalSystemSailplaneFlightsPostParams struct {

	/* InputEntity.

	   SailplaneFlight to be created
	*/
	InputEntity *models.ExternalSystemSailplaneFlightInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system sailplane flights post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSailplaneFlightsPostParams) WithDefaults() *ExternalSystemSailplaneFlightsPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system sailplane flights post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSailplaneFlightsPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system sailplane flights post params
func (o *ExternalSystemSailplaneFlightsPostParams) WithTimeout(timeout time.Duration) *ExternalSystemSailplaneFlightsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system sailplane flights post params
func (o *ExternalSystemSailplaneFlightsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system sailplane flights post params
func (o *ExternalSystemSailplaneFlightsPostParams) WithContext(ctx context.Context) *ExternalSystemSailplaneFlightsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system sailplane flights post params
func (o *ExternalSystemSailplaneFlightsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system sailplane flights post params
func (o *ExternalSystemSailplaneFlightsPostParams) WithHTTPClient(client *http.Client) *ExternalSystemSailplaneFlightsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system sailplane flights post params
func (o *ExternalSystemSailplaneFlightsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInputEntity adds the inputEntity to the external system sailplane flights post params
func (o *ExternalSystemSailplaneFlightsPostParams) WithInputEntity(inputEntity *models.ExternalSystemSailplaneFlightInput) *ExternalSystemSailplaneFlightsPostParams {
	o.SetInputEntity(inputEntity)
	return o
}

// SetInputEntity adds the inputEntity to the external system sailplane flights post params
func (o *ExternalSystemSailplaneFlightsPostParams) SetInputEntity(inputEntity *models.ExternalSystemSailplaneFlightInput) {
	o.InputEntity = inputEntity
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemSailplaneFlightsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.InputEntity != nil {
		if err := r.SetBodyParam(o.InputEntity); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
