// Code generated by go-swagger; DO NOT EDIT.

package external_system_sailplane_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExternalSystemSailplaneFlightsDeleteReader is a Reader for the ExternalSystemSailplaneFlightsDelete structure.
type ExternalSystemSailplaneFlightsDeleteReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSailplaneFlightsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSailplaneFlightsDeleteOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/pel/public/externalsystemsailplaneflights/{id}] ExternalSystemSailplaneFlights_Delete", response, response.Code())
	}
}

// NewExternalSystemSailplaneFlightsDeleteOK creates a ExternalSystemSailplaneFlightsDeleteOK with default headers values
func NewExternalSystemSailplaneFlightsDeleteOK(writer io.Writer) *ExternalSystemSailplaneFlightsDeleteOK {
	return &ExternalSystemSailplaneFlightsDeleteOK{

		Payload: writer,
	}
}

/*
ExternalSystemSailplaneFlightsDeleteOK describes a response with status code 200, with default header values.

ExternalSystemSailplaneFlightsDeleteOK external system sailplane flights delete o k
*/
type ExternalSystemSailplaneFlightsDeleteOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this external system sailplane flights delete o k response has a 2xx status code
func (o *ExternalSystemSailplaneFlightsDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this external system sailplane flights delete o k response has a 3xx status code
func (o *ExternalSystemSailplaneFlightsDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this external system sailplane flights delete o k response has a 4xx status code
func (o *ExternalSystemSailplaneFlightsDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this external system sailplane flights delete o k response has a 5xx status code
func (o *ExternalSystemSailplaneFlightsDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this external system sailplane flights delete o k response a status code equal to that given
func (o *ExternalSystemSailplaneFlightsDeleteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the external system sailplane flights delete o k response
func (o *ExternalSystemSailplaneFlightsDeleteOK) Code() int {
	return 200
}

func (o *ExternalSystemSailplaneFlightsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/pel/public/externalsystemsailplaneflights/{id}][%d] externalSystemSailplaneFlightsDeleteOK", 200)
}

func (o *ExternalSystemSailplaneFlightsDeleteOK) String() string {
	return fmt.Sprintf("[DELETE /api/pel/public/externalsystemsailplaneflights/{id}][%d] externalSystemSailplaneFlightsDeleteOK", 200)
}

func (o *ExternalSystemSailplaneFlightsDeleteOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ExternalSystemSailplaneFlightsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
