// Code generated by go-swagger; DO NOT EDIT.

package external_system_sailplane_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExternalSystemSailplaneFlightsDeleteParams creates a new ExternalSystemSailplaneFlightsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemSailplaneFlightsDeleteParams() *ExternalSystemSailplaneFlightsDeleteParams {
	return &ExternalSystemSailplaneFlightsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemSailplaneFlightsDeleteParamsWithTimeout creates a new ExternalSystemSailplaneFlightsDeleteParams object
// with the ability to set a timeout on a request.
func NewExternalSystemSailplaneFlightsDeleteParamsWithTimeout(timeout time.Duration) *ExternalSystemSailplaneFlightsDeleteParams {
	return &ExternalSystemSailplaneFlightsDeleteParams{
		timeout: timeout,
	}
}

// NewExternalSystemSailplaneFlightsDeleteParamsWithContext creates a new ExternalSystemSailplaneFlightsDeleteParams object
// with the ability to set a context for a request.
func NewExternalSystemSailplaneFlightsDeleteParamsWithContext(ctx context.Context) *ExternalSystemSailplaneFlightsDeleteParams {
	return &ExternalSystemSailplaneFlightsDeleteParams{
		Context: ctx,
	}
}

// NewExternalSystemSailplaneFlightsDeleteParamsWithHTTPClient creates a new ExternalSystemSailplaneFlightsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemSailplaneFlightsDeleteParamsWithHTTPClient(client *http.Client) *ExternalSystemSailplaneFlightsDeleteParams {
	return &ExternalSystemSailplaneFlightsDeleteParams{
		HTTPClient: client,
	}
}

/* ExternalSystemSailplaneFlightsDeleteParams contains all the parameters to send to the API endpoint
   for the external system sailplane flights delete operation.

   Typically these are written to a http.Request.
*/
type ExternalSystemSailplaneFlightsDeleteParams struct {

	/* ID.

	   The ExternalSystemUniqueID of the sailplaneFlight to be deleted
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system sailplane flights delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSailplaneFlightsDeleteParams) WithDefaults() *ExternalSystemSailplaneFlightsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system sailplane flights delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSailplaneFlightsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system sailplane flights delete params
func (o *ExternalSystemSailplaneFlightsDeleteParams) WithTimeout(timeout time.Duration) *ExternalSystemSailplaneFlightsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system sailplane flights delete params
func (o *ExternalSystemSailplaneFlightsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system sailplane flights delete params
func (o *ExternalSystemSailplaneFlightsDeleteParams) WithContext(ctx context.Context) *ExternalSystemSailplaneFlightsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system sailplane flights delete params
func (o *ExternalSystemSailplaneFlightsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system sailplane flights delete params
func (o *ExternalSystemSailplaneFlightsDeleteParams) WithHTTPClient(client *http.Client) *ExternalSystemSailplaneFlightsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system sailplane flights delete params
func (o *ExternalSystemSailplaneFlightsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the external system sailplane flights delete params
func (o *ExternalSystemSailplaneFlightsDeleteParams) WithID(id string) *ExternalSystemSailplaneFlightsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the external system sailplane flights delete params
func (o *ExternalSystemSailplaneFlightsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemSailplaneFlightsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
