// Code generated by go-swagger; DO NOT EDIT.

package external_system_sailplane_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExternalSystemSailplaneFlightsGetParams creates a new ExternalSystemSailplaneFlightsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemSailplaneFlightsGetParams() *ExternalSystemSailplaneFlightsGetParams {
	return &ExternalSystemSailplaneFlightsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemSailplaneFlightsGetParamsWithTimeout creates a new ExternalSystemSailplaneFlightsGetParams object
// with the ability to set a timeout on a request.
func NewExternalSystemSailplaneFlightsGetParamsWithTimeout(timeout time.Duration) *ExternalSystemSailplaneFlightsGetParams {
	return &ExternalSystemSailplaneFlightsGetParams{
		timeout: timeout,
	}
}

// NewExternalSystemSailplaneFlightsGetParamsWithContext creates a new ExternalSystemSailplaneFlightsGetParams object
// with the ability to set a context for a request.
func NewExternalSystemSailplaneFlightsGetParamsWithContext(ctx context.Context) *ExternalSystemSailplaneFlightsGetParams {
	return &ExternalSystemSailplaneFlightsGetParams{
		Context: ctx,
	}
}

// NewExternalSystemSailplaneFlightsGetParamsWithHTTPClient creates a new ExternalSystemSailplaneFlightsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemSailplaneFlightsGetParamsWithHTTPClient(client *http.Client) *ExternalSystemSailplaneFlightsGetParams {
	return &ExternalSystemSailplaneFlightsGetParams{
		HTTPClient: client,
	}
}

/* ExternalSystemSailplaneFlightsGetParams contains all the parameters to send to the API endpoint
   for the external system sailplane flights get operation.

   Typically these are written to a http.Request.
*/
type ExternalSystemSailplaneFlightsGetParams struct {

	/* ID.

	   The ExternalSystemUniqueID of the sailplaneFlight to retrieve
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system sailplane flights get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSailplaneFlightsGetParams) WithDefaults() *ExternalSystemSailplaneFlightsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system sailplane flights get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSailplaneFlightsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system sailplane flights get params
func (o *ExternalSystemSailplaneFlightsGetParams) WithTimeout(timeout time.Duration) *ExternalSystemSailplaneFlightsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system sailplane flights get params
func (o *ExternalSystemSailplaneFlightsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system sailplane flights get params
func (o *ExternalSystemSailplaneFlightsGetParams) WithContext(ctx context.Context) *ExternalSystemSailplaneFlightsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system sailplane flights get params
func (o *ExternalSystemSailplaneFlightsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system sailplane flights get params
func (o *ExternalSystemSailplaneFlightsGetParams) WithHTTPClient(client *http.Client) *ExternalSystemSailplaneFlightsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system sailplane flights get params
func (o *ExternalSystemSailplaneFlightsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the external system sailplane flights get params
func (o *ExternalSystemSailplaneFlightsGetParams) WithID(id string) *ExternalSystemSailplaneFlightsGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the external system sailplane flights get params
func (o *ExternalSystemSailplaneFlightsGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemSailplaneFlightsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
