// Code generated by go-swagger; DO NOT EDIT.

package external_system_sailplane_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemSailplaneFlightsPutReader is a Reader for the ExternalSystemSailplaneFlightsPut structure.
type ExternalSystemSailplaneFlightsPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSailplaneFlightsPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSailplaneFlightsPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/pel/public/externalsystemsailplaneflights/{id}] ExternalSystemSailplaneFlights_Put", response, response.Code())
	}
}

// NewExternalSystemSailplaneFlightsPutOK creates a ExternalSystemSailplaneFlightsPutOK with default headers values
func NewExternalSystemSailplaneFlightsPutOK() *ExternalSystemSailplaneFlightsPutOK {
	return &ExternalSystemSailplaneFlightsPutOK{}
}

/*
ExternalSystemSailplaneFlightsPutOK describes a response with status code 200, with default header values.

ExternalSystemSailplaneFlightsPutOK external system sailplane flights put o k
*/
type ExternalSystemSailplaneFlightsPutOK struct {
	Payload *models.ExternalSystemSailplaneFlightOutput
}

// IsSuccess returns true when this external system sailplane flights put o k response has a 2xx status code
func (o *ExternalSystemSailplaneFlightsPutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this external system sailplane flights put o k response has a 3xx status code
func (o *ExternalSystemSailplaneFlightsPutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this external system sailplane flights put o k response has a 4xx status code
func (o *ExternalSystemSailplaneFlightsPutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this external system sailplane flights put o k response has a 5xx status code
func (o *ExternalSystemSailplaneFlightsPutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this external system sailplane flights put o k response a status code equal to that given
func (o *ExternalSystemSailplaneFlightsPutOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the external system sailplane flights put o k response
func (o *ExternalSystemSailplaneFlightsPutOK) Code() int {
	return 200
}

func (o *ExternalSystemSailplaneFlightsPutOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pel/public/externalsystemsailplaneflights/{id}][%d] externalSystemSailplaneFlightsPutOK %s", 200, payload)
}

func (o *ExternalSystemSailplaneFlightsPutOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pel/public/externalsystemsailplaneflights/{id}][%d] externalSystemSailplaneFlightsPutOK %s", 200, payload)
}

func (o *ExternalSystemSailplaneFlightsPutOK) GetPayload() *models.ExternalSystemSailplaneFlightOutput {
	return o.Payload
}

func (o *ExternalSystemSailplaneFlightsPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemSailplaneFlightOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
