// Code generated by go-swagger; DO NOT EDIT.

package external_system_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExternalSystemFlightsDeleteParams creates a new ExternalSystemFlightsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemFlightsDeleteParams() *ExternalSystemFlightsDeleteParams {
	return &ExternalSystemFlightsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemFlightsDeleteParamsWithTimeout creates a new ExternalSystemFlightsDeleteParams object
// with the ability to set a timeout on a request.
func NewExternalSystemFlightsDeleteParamsWithTimeout(timeout time.Duration) *ExternalSystemFlightsDeleteParams {
	return &ExternalSystemFlightsDeleteParams{
		timeout: timeout,
	}
}

// NewExternalSystemFlightsDeleteParamsWithContext creates a new ExternalSystemFlightsDeleteParams object
// with the ability to set a context for a request.
func NewExternalSystemFlightsDeleteParamsWithContext(ctx context.Context) *ExternalSystemFlightsDeleteParams {
	return &ExternalSystemFlightsDeleteParams{
		Context: ctx,
	}
}

// NewExternalSystemFlightsDeleteParamsWithHTTPClient creates a new ExternalSystemFlightsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemFlightsDeleteParamsWithHTTPClient(client *http.Client) *ExternalSystemFlightsDeleteParams {
	return &ExternalSystemFlightsDeleteParams{
		HTTPClient: client,
	}
}

/* ExternalSystemFlightsDeleteParams contains all the parameters to send to the API endpoint
   for the external system flights delete operation.

   Typically these are written to a http.Request.
*/
type ExternalSystemFlightsDeleteParams struct {

	/* ID.

	   The ExternalSystemUniqueID of the flight to be deleted
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system flights delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemFlightsDeleteParams) WithDefaults() *ExternalSystemFlightsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system flights delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemFlightsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system flights delete params
func (o *ExternalSystemFlightsDeleteParams) WithTimeout(timeout time.Duration) *ExternalSystemFlightsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system flights delete params
func (o *ExternalSystemFlightsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system flights delete params
func (o *ExternalSystemFlightsDeleteParams) WithContext(ctx context.Context) *ExternalSystemFlightsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system flights delete params
func (o *ExternalSystemFlightsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system flights delete params
func (o *ExternalSystemFlightsDeleteParams) WithHTTPClient(client *http.Client) *ExternalSystemFlightsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system flights delete params
func (o *ExternalSystemFlightsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the external system flights delete params
func (o *ExternalSystemFlightsDeleteParams) WithID(id string) *ExternalSystemFlightsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the external system flights delete params
func (o *ExternalSystemFlightsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemFlightsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
