// Code generated by go-swagger; DO NOT EDIT.

package external_system_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExternalSystemFlightsPostMultipleReader is a Reader for the ExternalSystemFlightsPostMultiple structure.
type ExternalSystemFlightsPostMultipleReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemFlightsPostMultipleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemFlightsPostMultipleOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExternalSystemFlightsPostMultipleOK creates a ExternalSystemFlightsPostMultipleOK with default headers values
func NewExternalSystemFlightsPostMultipleOK(writer io.Writer) *ExternalSystemFlightsPostMultipleOK {
	return &ExternalSystemFlightsPostMultipleOK{

		Payload: writer,
	}
}

/* ExternalSystemFlightsPostMultipleOK describes a response with status code 200, with default header values.

ExternalSystemFlightsPostMultipleOK external system flights post multiple o k
*/
type ExternalSystemFlightsPostMultipleOK struct {
	Payload io.Writer
}

func (o *ExternalSystemFlightsPostMultipleOK) Error() string {
	return fmt.Sprintf("[POST /api/pel/public/externalsystemflights/PostMultiple][%d] externalSystemFlightsPostMultipleOK  %+v", 200, o.Payload)
}
func (o *ExternalSystemFlightsPostMultipleOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ExternalSystemFlightsPostMultipleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
