// Code generated by go-swagger; DO NOT EDIT.

package external_system_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExternalSystemFlightsDeleteReader is a Reader for the ExternalSystemFlightsDelete structure.
type ExternalSystemFlightsDeleteReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemFlightsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemFlightsDeleteOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExternalSystemFlightsDeleteOK creates a ExternalSystemFlightsDeleteOK with default headers values
func NewExternalSystemFlightsDeleteOK(writer io.Writer) *ExternalSystemFlightsDeleteOK {
	return &ExternalSystemFlightsDeleteOK{

		Payload: writer,
	}
}

/* ExternalSystemFlightsDeleteOK describes a response with status code 200, with default header values.

ExternalSystemFlightsDeleteOK external system flights delete o k
*/
type ExternalSystemFlightsDeleteOK struct {
	Payload io.Writer
}

func (o *ExternalSystemFlightsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/pel/public/externalsystemflights/{id}][%d] externalSystemFlightsDeleteOK  %+v", 200, o.Payload)
}
func (o *ExternalSystemFlightsDeleteOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ExternalSystemFlightsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
