// Code generated by go-swagger; DO NOT EDIT.

package external_system_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// NewExternalSystemFlightsPutParams creates a new ExternalSystemFlightsPutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemFlightsPutParams() *ExternalSystemFlightsPutParams {
	return &ExternalSystemFlightsPutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemFlightsPutParamsWithTimeout creates a new ExternalSystemFlightsPutParams object
// with the ability to set a timeout on a request.
func NewExternalSystemFlightsPutParamsWithTimeout(timeout time.Duration) *ExternalSystemFlightsPutParams {
	return &ExternalSystemFlightsPutParams{
		timeout: timeout,
	}
}

// NewExternalSystemFlightsPutParamsWithContext creates a new ExternalSystemFlightsPutParams object
// with the ability to set a context for a request.
func NewExternalSystemFlightsPutParamsWithContext(ctx context.Context) *ExternalSystemFlightsPutParams {
	return &ExternalSystemFlightsPutParams{
		Context: ctx,
	}
}

// NewExternalSystemFlightsPutParamsWithHTTPClient creates a new ExternalSystemFlightsPutParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemFlightsPutParamsWithHTTPClient(client *http.Client) *ExternalSystemFlightsPutParams {
	return &ExternalSystemFlightsPutParams{
		HTTPClient: client,
	}
}

/*
ExternalSystemFlightsPutParams contains all the parameters to send to the API endpoint

	for the external system flights put operation.

	Typically these are written to a http.Request.
*/
type ExternalSystemFlightsPutParams struct {

	/* ID.

	   The ExternalSystemUniqueID of the flight to be modified
	*/
	ID string

	/* InputEntity.

	   Full data of the flight to be edited
	*/
	InputEntity *models.ExternalSystemFlightInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system flights put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemFlightsPutParams) WithDefaults() *ExternalSystemFlightsPutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system flights put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemFlightsPutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system flights put params
func (o *ExternalSystemFlightsPutParams) WithTimeout(timeout time.Duration) *ExternalSystemFlightsPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system flights put params
func (o *ExternalSystemFlightsPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system flights put params
func (o *ExternalSystemFlightsPutParams) WithContext(ctx context.Context) *ExternalSystemFlightsPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system flights put params
func (o *ExternalSystemFlightsPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system flights put params
func (o *ExternalSystemFlightsPutParams) WithHTTPClient(client *http.Client) *ExternalSystemFlightsPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system flights put params
func (o *ExternalSystemFlightsPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the external system flights put params
func (o *ExternalSystemFlightsPutParams) WithID(id string) *ExternalSystemFlightsPutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the external system flights put params
func (o *ExternalSystemFlightsPutParams) SetID(id string) {
	o.ID = id
}

// WithInputEntity adds the inputEntity to the external system flights put params
func (o *ExternalSystemFlightsPutParams) WithInputEntity(inputEntity *models.ExternalSystemFlightInput) *ExternalSystemFlightsPutParams {
	o.SetInputEntity(inputEntity)
	return o
}

// SetInputEntity adds the inputEntity to the external system flights put params
func (o *ExternalSystemFlightsPutParams) SetInputEntity(inputEntity *models.ExternalSystemFlightInput) {
	o.InputEntity = inputEntity
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemFlightsPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.InputEntity != nil {
		if err := r.SetBodyParam(o.InputEntity); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
