// Code generated by go-swagger; DO NOT EDIT.

package external_system_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemFlightsPutReader is a Reader for the ExternalSystemFlightsPut structure.
type ExternalSystemFlightsPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemFlightsPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemFlightsPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExternalSystemFlightsPutOK creates a ExternalSystemFlightsPutOK with default headers values
func NewExternalSystemFlightsPutOK() *ExternalSystemFlightsPutOK {
	return &ExternalSystemFlightsPutOK{}
}

/* ExternalSystemFlightsPutOK describes a response with status code 200, with default header values.

ExternalSystemFlightsPutOK external system flights put o k
*/
type ExternalSystemFlightsPutOK struct {
	Payload *models.ExternalSystemFlightOutput
}

func (o *ExternalSystemFlightsPutOK) Error() string {
	return fmt.Sprintf("[PUT /api/pel/public/externalsystemflights/{id}][%d] externalSystemFlightsPutOK  %+v", 200, o.Payload)
}
func (o *ExternalSystemFlightsPutOK) GetPayload() *models.ExternalSystemFlightOutput {
	return o.Payload
}

func (o *ExternalSystemFlightsPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemFlightOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
