// Code generated by go-swagger; DO NOT EDIT.

package external_system_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemFlightsPostReader is a Reader for the ExternalSystemFlightsPost structure.
type ExternalSystemFlightsPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemFlightsPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemFlightsPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExternalSystemFlightsPostOK creates a ExternalSystemFlightsPostOK with default headers values
func NewExternalSystemFlightsPostOK() *ExternalSystemFlightsPostOK {
	return &ExternalSystemFlightsPostOK{}
}

/* ExternalSystemFlightsPostOK describes a response with status code 200, with default header values.

ExternalSystemFlightsPostOK external system flights post o k
*/
type ExternalSystemFlightsPostOK struct {
	Payload *models.ExternalSystemFlightOutput
}

func (o *ExternalSystemFlightsPostOK) Error() string {
	return fmt.Sprintf("[POST /api/pel/public/externalsystemflights][%d] externalSystemFlightsPostOK  %+v", 200, o.Payload)
}
func (o *ExternalSystemFlightsPostOK) GetPayload() *models.ExternalSystemFlightOutput {
	return o.Payload
}

func (o *ExternalSystemFlightsPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemFlightOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
