// Code generated by go-swagger; DO NOT EDIT.

package external_system_balloon_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemBalloonFlightsPostReader is a Reader for the ExternalSystemBalloonFlightsPost structure.
type ExternalSystemBalloonFlightsPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemBalloonFlightsPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemBalloonFlightsPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/pel/public/externalsystemballoonflights] ExternalSystemBalloonFlights_Post", response, response.Code())
	}
}

// NewExternalSystemBalloonFlightsPostOK creates a ExternalSystemBalloonFlightsPostOK with default headers values
func NewExternalSystemBalloonFlightsPostOK() *ExternalSystemBalloonFlightsPostOK {
	return &ExternalSystemBalloonFlightsPostOK{}
}

/*
ExternalSystemBalloonFlightsPostOK describes a response with status code 200, with default header values.

ExternalSystemBalloonFlightsPostOK external system balloon flights post o k
*/
type ExternalSystemBalloonFlightsPostOK struct {
	Payload *models.ExternalSystemBalloonFlightOutput
}

// IsSuccess returns true when this external system balloon flights post o k response has a 2xx status code
func (o *ExternalSystemBalloonFlightsPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this external system balloon flights post o k response has a 3xx status code
func (o *ExternalSystemBalloonFlightsPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this external system balloon flights post o k response has a 4xx status code
func (o *ExternalSystemBalloonFlightsPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this external system balloon flights post o k response has a 5xx status code
func (o *ExternalSystemBalloonFlightsPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this external system balloon flights post o k response a status code equal to that given
func (o *ExternalSystemBalloonFlightsPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the external system balloon flights post o k response
func (o *ExternalSystemBalloonFlightsPostOK) Code() int {
	return 200
}

func (o *ExternalSystemBalloonFlightsPostOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/pel/public/externalsystemballoonflights][%d] externalSystemBalloonFlightsPostOK %s", 200, payload)
}

func (o *ExternalSystemBalloonFlightsPostOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/pel/public/externalsystemballoonflights][%d] externalSystemBalloonFlightsPostOK %s", 200, payload)
}

func (o *ExternalSystemBalloonFlightsPostOK) GetPayload() *models.ExternalSystemBalloonFlightOutput {
	return o.Payload
}

func (o *ExternalSystemBalloonFlightsPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemBalloonFlightOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
