// Code generated by go-swagger; DO NOT EDIT.

package external_system_balloon_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExternalSystemBalloonFlightsDeleteParams creates a new ExternalSystemBalloonFlightsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemBalloonFlightsDeleteParams() *ExternalSystemBalloonFlightsDeleteParams {
	return &ExternalSystemBalloonFlightsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemBalloonFlightsDeleteParamsWithTimeout creates a new ExternalSystemBalloonFlightsDeleteParams object
// with the ability to set a timeout on a request.
func NewExternalSystemBalloonFlightsDeleteParamsWithTimeout(timeout time.Duration) *ExternalSystemBalloonFlightsDeleteParams {
	return &ExternalSystemBalloonFlightsDeleteParams{
		timeout: timeout,
	}
}

// NewExternalSystemBalloonFlightsDeleteParamsWithContext creates a new ExternalSystemBalloonFlightsDeleteParams object
// with the ability to set a context for a request.
func NewExternalSystemBalloonFlightsDeleteParamsWithContext(ctx context.Context) *ExternalSystemBalloonFlightsDeleteParams {
	return &ExternalSystemBalloonFlightsDeleteParams{
		Context: ctx,
	}
}

// NewExternalSystemBalloonFlightsDeleteParamsWithHTTPClient creates a new ExternalSystemBalloonFlightsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemBalloonFlightsDeleteParamsWithHTTPClient(client *http.Client) *ExternalSystemBalloonFlightsDeleteParams {
	return &ExternalSystemBalloonFlightsDeleteParams{
		HTTPClient: client,
	}
}

/* ExternalSystemBalloonFlightsDeleteParams contains all the parameters to send to the API endpoint
   for the external system balloon flights delete operation.

   Typically these are written to a http.Request.
*/
type ExternalSystemBalloonFlightsDeleteParams struct {

	/* ID.

	   The ExternalSystemUniqueID of the balloonFlight to be deleted
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system balloon flights delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemBalloonFlightsDeleteParams) WithDefaults() *ExternalSystemBalloonFlightsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system balloon flights delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemBalloonFlightsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system balloon flights delete params
func (o *ExternalSystemBalloonFlightsDeleteParams) WithTimeout(timeout time.Duration) *ExternalSystemBalloonFlightsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system balloon flights delete params
func (o *ExternalSystemBalloonFlightsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system balloon flights delete params
func (o *ExternalSystemBalloonFlightsDeleteParams) WithContext(ctx context.Context) *ExternalSystemBalloonFlightsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system balloon flights delete params
func (o *ExternalSystemBalloonFlightsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system balloon flights delete params
func (o *ExternalSystemBalloonFlightsDeleteParams) WithHTTPClient(client *http.Client) *ExternalSystemBalloonFlightsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system balloon flights delete params
func (o *ExternalSystemBalloonFlightsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the external system balloon flights delete params
func (o *ExternalSystemBalloonFlightsDeleteParams) WithID(id string) *ExternalSystemBalloonFlightsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the external system balloon flights delete params
func (o *ExternalSystemBalloonFlightsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemBalloonFlightsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
