// Code generated by go-swagger; DO NOT EDIT.

package external_system_balloon_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExternalSystemBalloonFlightsPostMultipleReader is a Reader for the ExternalSystemBalloonFlightsPostMultiple structure.
type ExternalSystemBalloonFlightsPostMultipleReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemBalloonFlightsPostMultipleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemBalloonFlightsPostMultipleOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExternalSystemBalloonFlightsPostMultipleOK creates a ExternalSystemBalloonFlightsPostMultipleOK with default headers values
func NewExternalSystemBalloonFlightsPostMultipleOK(writer io.Writer) *ExternalSystemBalloonFlightsPostMultipleOK {
	return &ExternalSystemBalloonFlightsPostMultipleOK{

		Payload: writer,
	}
}

/* ExternalSystemBalloonFlightsPostMultipleOK describes a response with status code 200, with default header values.

ExternalSystemBalloonFlightsPostMultipleOK external system balloon flights post multiple o k
*/
type ExternalSystemBalloonFlightsPostMultipleOK struct {
	Payload io.Writer
}

func (o *ExternalSystemBalloonFlightsPostMultipleOK) Error() string {
	return fmt.Sprintf("[POST /api/pel/public/externalsystemballoonflights/PostMultiple][%d] externalSystemBalloonFlightsPostMultipleOK  %+v", 200, o.Payload)
}
func (o *ExternalSystemBalloonFlightsPostMultipleOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ExternalSystemBalloonFlightsPostMultipleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
