// Code generated by go-swagger; DO NOT EDIT.

package external_system_balloon_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// NewExternalSystemBalloonFlightsPostMultipleParams creates a new ExternalSystemBalloonFlightsPostMultipleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemBalloonFlightsPostMultipleParams() *ExternalSystemBalloonFlightsPostMultipleParams {
	return &ExternalSystemBalloonFlightsPostMultipleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemBalloonFlightsPostMultipleParamsWithTimeout creates a new ExternalSystemBalloonFlightsPostMultipleParams object
// with the ability to set a timeout on a request.
func NewExternalSystemBalloonFlightsPostMultipleParamsWithTimeout(timeout time.Duration) *ExternalSystemBalloonFlightsPostMultipleParams {
	return &ExternalSystemBalloonFlightsPostMultipleParams{
		timeout: timeout,
	}
}

// NewExternalSystemBalloonFlightsPostMultipleParamsWithContext creates a new ExternalSystemBalloonFlightsPostMultipleParams object
// with the ability to set a context for a request.
func NewExternalSystemBalloonFlightsPostMultipleParamsWithContext(ctx context.Context) *ExternalSystemBalloonFlightsPostMultipleParams {
	return &ExternalSystemBalloonFlightsPostMultipleParams{
		Context: ctx,
	}
}

// NewExternalSystemBalloonFlightsPostMultipleParamsWithHTTPClient creates a new ExternalSystemBalloonFlightsPostMultipleParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemBalloonFlightsPostMultipleParamsWithHTTPClient(client *http.Client) *ExternalSystemBalloonFlightsPostMultipleParams {
	return &ExternalSystemBalloonFlightsPostMultipleParams{
		HTTPClient: client,
	}
}

/*
ExternalSystemBalloonFlightsPostMultipleParams contains all the parameters to send to the API endpoint

	for the external system balloon flights post multiple operation.

	Typically these are written to a http.Request.
*/
type ExternalSystemBalloonFlightsPostMultipleParams struct {

	/* InputEntities.

	   Balloon flights to be created
	*/
	InputEntities []*models.ExternalSystemBalloonFlightInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system balloon flights post multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemBalloonFlightsPostMultipleParams) WithDefaults() *ExternalSystemBalloonFlightsPostMultipleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system balloon flights post multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemBalloonFlightsPostMultipleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system balloon flights post multiple params
func (o *ExternalSystemBalloonFlightsPostMultipleParams) WithTimeout(timeout time.Duration) *ExternalSystemBalloonFlightsPostMultipleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system balloon flights post multiple params
func (o *ExternalSystemBalloonFlightsPostMultipleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system balloon flights post multiple params
func (o *ExternalSystemBalloonFlightsPostMultipleParams) WithContext(ctx context.Context) *ExternalSystemBalloonFlightsPostMultipleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system balloon flights post multiple params
func (o *ExternalSystemBalloonFlightsPostMultipleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system balloon flights post multiple params
func (o *ExternalSystemBalloonFlightsPostMultipleParams) WithHTTPClient(client *http.Client) *ExternalSystemBalloonFlightsPostMultipleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system balloon flights post multiple params
func (o *ExternalSystemBalloonFlightsPostMultipleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInputEntities adds the inputEntities to the external system balloon flights post multiple params
func (o *ExternalSystemBalloonFlightsPostMultipleParams) WithInputEntities(inputEntities []*models.ExternalSystemBalloonFlightInput) *ExternalSystemBalloonFlightsPostMultipleParams {
	o.SetInputEntities(inputEntities)
	return o
}

// SetInputEntities adds the inputEntities to the external system balloon flights post multiple params
func (o *ExternalSystemBalloonFlightsPostMultipleParams) SetInputEntities(inputEntities []*models.ExternalSystemBalloonFlightInput) {
	o.InputEntities = inputEntities
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemBalloonFlightsPostMultipleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.InputEntities != nil {
		if err := r.SetBodyParam(o.InputEntities); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
