// Code generated by go-swagger; DO NOT EDIT.

package external_system_balloon_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExternalSystemBalloonFlightsGetParams creates a new ExternalSystemBalloonFlightsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemBalloonFlightsGetParams() *ExternalSystemBalloonFlightsGetParams {
	return &ExternalSystemBalloonFlightsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemBalloonFlightsGetParamsWithTimeout creates a new ExternalSystemBalloonFlightsGetParams object
// with the ability to set a timeout on a request.
func NewExternalSystemBalloonFlightsGetParamsWithTimeout(timeout time.Duration) *ExternalSystemBalloonFlightsGetParams {
	return &ExternalSystemBalloonFlightsGetParams{
		timeout: timeout,
	}
}

// NewExternalSystemBalloonFlightsGetParamsWithContext creates a new ExternalSystemBalloonFlightsGetParams object
// with the ability to set a context for a request.
func NewExternalSystemBalloonFlightsGetParamsWithContext(ctx context.Context) *ExternalSystemBalloonFlightsGetParams {
	return &ExternalSystemBalloonFlightsGetParams{
		Context: ctx,
	}
}

// NewExternalSystemBalloonFlightsGetParamsWithHTTPClient creates a new ExternalSystemBalloonFlightsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemBalloonFlightsGetParamsWithHTTPClient(client *http.Client) *ExternalSystemBalloonFlightsGetParams {
	return &ExternalSystemBalloonFlightsGetParams{
		HTTPClient: client,
	}
}

/* ExternalSystemBalloonFlightsGetParams contains all the parameters to send to the API endpoint
   for the external system balloon flights get operation.

   Typically these are written to a http.Request.
*/
type ExternalSystemBalloonFlightsGetParams struct {

	/* ID.

	   The ExternalSystemUniqueID of the balloonFlight to retrieve
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system balloon flights get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemBalloonFlightsGetParams) WithDefaults() *ExternalSystemBalloonFlightsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system balloon flights get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemBalloonFlightsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system balloon flights get params
func (o *ExternalSystemBalloonFlightsGetParams) WithTimeout(timeout time.Duration) *ExternalSystemBalloonFlightsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system balloon flights get params
func (o *ExternalSystemBalloonFlightsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system balloon flights get params
func (o *ExternalSystemBalloonFlightsGetParams) WithContext(ctx context.Context) *ExternalSystemBalloonFlightsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system balloon flights get params
func (o *ExternalSystemBalloonFlightsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system balloon flights get params
func (o *ExternalSystemBalloonFlightsGetParams) WithHTTPClient(client *http.Client) *ExternalSystemBalloonFlightsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system balloon flights get params
func (o *ExternalSystemBalloonFlightsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the external system balloon flights get params
func (o *ExternalSystemBalloonFlightsGetParams) WithID(id string) *ExternalSystemBalloonFlightsGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the external system balloon flights get params
func (o *ExternalSystemBalloonFlightsGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemBalloonFlightsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
