// Code generated by go-swagger; DO NOT EDIT.

package external_system_balloon_flights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExternalSystemBalloonFlightsDeleteReader is a Reader for the ExternalSystemBalloonFlightsDelete structure.
type ExternalSystemBalloonFlightsDeleteReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemBalloonFlightsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemBalloonFlightsDeleteOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExternalSystemBalloonFlightsDeleteOK creates a ExternalSystemBalloonFlightsDeleteOK with default headers values
func NewExternalSystemBalloonFlightsDeleteOK(writer io.Writer) *ExternalSystemBalloonFlightsDeleteOK {
	return &ExternalSystemBalloonFlightsDeleteOK{

		Payload: writer,
	}
}

/* ExternalSystemBalloonFlightsDeleteOK describes a response with status code 200, with default header values.

ExternalSystemBalloonFlightsDeleteOK external system balloon flights delete o k
*/
type ExternalSystemBalloonFlightsDeleteOK struct {
	Payload io.Writer
}

func (o *ExternalSystemBalloonFlightsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/pel/public/externalsystemballoonflights/{id}][%d] externalSystemBalloonFlightsDeleteOK  %+v", 200, o.Payload)
}
func (o *ExternalSystemBalloonFlightsDeleteOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ExternalSystemBalloonFlightsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
