// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExternalSystemSimulatorSessionsPostMultipleReader is a Reader for the ExternalSystemSimulatorSessionsPostMultiple structure.
type ExternalSystemSimulatorSessionsPostMultipleReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSimulatorSessionsPostMultipleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSimulatorSessionsPostMultipleOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExternalSystemSimulatorSessionsPostMultipleOK creates a ExternalSystemSimulatorSessionsPostMultipleOK with default headers values
func NewExternalSystemSimulatorSessionsPostMultipleOK(writer io.Writer) *ExternalSystemSimulatorSessionsPostMultipleOK {
	return &ExternalSystemSimulatorSessionsPostMultipleOK{

		Payload: writer,
	}
}

/* ExternalSystemSimulatorSessionsPostMultipleOK describes a response with status code 200, with default header values.

ExternalSystemSimulatorSessionsPostMultipleOK external system simulator sessions post multiple o k
*/
type ExternalSystemSimulatorSessionsPostMultipleOK struct {
	Payload io.Writer
}

func (o *ExternalSystemSimulatorSessionsPostMultipleOK) Error() string {
	return fmt.Sprintf("[POST /api/pel/public/externalsystemsimulatorSessions/PostMultiple][%d] externalSystemSimulatorSessionsPostMultipleOK  %+v", 200, o.Payload)
}
func (o *ExternalSystemSimulatorSessionsPostMultipleOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ExternalSystemSimulatorSessionsPostMultipleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
