// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExternalSystemSimulatorSessionsDeleteReader is a Reader for the ExternalSystemSimulatorSessionsDelete structure.
type ExternalSystemSimulatorSessionsDeleteReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSimulatorSessionsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSimulatorSessionsDeleteOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/pel/public/externalsystemsimulatorsessions/{id}] ExternalSystemSimulatorSessions_Delete", response, response.Code())
	}
}

// NewExternalSystemSimulatorSessionsDeleteOK creates a ExternalSystemSimulatorSessionsDeleteOK with default headers values
func NewExternalSystemSimulatorSessionsDeleteOK(writer io.Writer) *ExternalSystemSimulatorSessionsDeleteOK {
	return &ExternalSystemSimulatorSessionsDeleteOK{

		Payload: writer,
	}
}

/*
ExternalSystemSimulatorSessionsDeleteOK describes a response with status code 200, with default header values.

ExternalSystemSimulatorSessionsDeleteOK external system simulator sessions delete o k
*/
type ExternalSystemSimulatorSessionsDeleteOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this external system simulator sessions delete o k response has a 2xx status code
func (o *ExternalSystemSimulatorSessionsDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this external system simulator sessions delete o k response has a 3xx status code
func (o *ExternalSystemSimulatorSessionsDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this external system simulator sessions delete o k response has a 4xx status code
func (o *ExternalSystemSimulatorSessionsDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this external system simulator sessions delete o k response has a 5xx status code
func (o *ExternalSystemSimulatorSessionsDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this external system simulator sessions delete o k response a status code equal to that given
func (o *ExternalSystemSimulatorSessionsDeleteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the external system simulator sessions delete o k response
func (o *ExternalSystemSimulatorSessionsDeleteOK) Code() int {
	return 200
}

func (o *ExternalSystemSimulatorSessionsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/pel/public/externalsystemsimulatorsessions/{id}][%d] externalSystemSimulatorSessionsDeleteOK", 200)
}

func (o *ExternalSystemSimulatorSessionsDeleteOK) String() string {
	return fmt.Sprintf("[DELETE /api/pel/public/externalsystemsimulatorsessions/{id}][%d] externalSystemSimulatorSessionsDeleteOK", 200)
}

func (o *ExternalSystemSimulatorSessionsDeleteOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ExternalSystemSimulatorSessionsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
