// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExternalSystemSimulatorSessionsDeleteParams creates a new ExternalSystemSimulatorSessionsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemSimulatorSessionsDeleteParams() *ExternalSystemSimulatorSessionsDeleteParams {
	return &ExternalSystemSimulatorSessionsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemSimulatorSessionsDeleteParamsWithTimeout creates a new ExternalSystemSimulatorSessionsDeleteParams object
// with the ability to set a timeout on a request.
func NewExternalSystemSimulatorSessionsDeleteParamsWithTimeout(timeout time.Duration) *ExternalSystemSimulatorSessionsDeleteParams {
	return &ExternalSystemSimulatorSessionsDeleteParams{
		timeout: timeout,
	}
}

// NewExternalSystemSimulatorSessionsDeleteParamsWithContext creates a new ExternalSystemSimulatorSessionsDeleteParams object
// with the ability to set a context for a request.
func NewExternalSystemSimulatorSessionsDeleteParamsWithContext(ctx context.Context) *ExternalSystemSimulatorSessionsDeleteParams {
	return &ExternalSystemSimulatorSessionsDeleteParams{
		Context: ctx,
	}
}

// NewExternalSystemSimulatorSessionsDeleteParamsWithHTTPClient creates a new ExternalSystemSimulatorSessionsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemSimulatorSessionsDeleteParamsWithHTTPClient(client *http.Client) *ExternalSystemSimulatorSessionsDeleteParams {
	return &ExternalSystemSimulatorSessionsDeleteParams{
		HTTPClient: client,
	}
}

/* ExternalSystemSimulatorSessionsDeleteParams contains all the parameters to send to the API endpoint
   for the external system simulator sessions delete operation.

   Typically these are written to a http.Request.
*/
type ExternalSystemSimulatorSessionsDeleteParams struct {

	/* ID.

	   The ExternalSystemUniqueID of the simulatorSession to be deleted
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system simulator sessions delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSimulatorSessionsDeleteParams) WithDefaults() *ExternalSystemSimulatorSessionsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system simulator sessions delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSimulatorSessionsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system simulator sessions delete params
func (o *ExternalSystemSimulatorSessionsDeleteParams) WithTimeout(timeout time.Duration) *ExternalSystemSimulatorSessionsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system simulator sessions delete params
func (o *ExternalSystemSimulatorSessionsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system simulator sessions delete params
func (o *ExternalSystemSimulatorSessionsDeleteParams) WithContext(ctx context.Context) *ExternalSystemSimulatorSessionsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system simulator sessions delete params
func (o *ExternalSystemSimulatorSessionsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system simulator sessions delete params
func (o *ExternalSystemSimulatorSessionsDeleteParams) WithHTTPClient(client *http.Client) *ExternalSystemSimulatorSessionsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system simulator sessions delete params
func (o *ExternalSystemSimulatorSessionsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the external system simulator sessions delete params
func (o *ExternalSystemSimulatorSessionsDeleteParams) WithID(id string) *ExternalSystemSimulatorSessionsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the external system simulator sessions delete params
func (o *ExternalSystemSimulatorSessionsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemSimulatorSessionsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
