// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExternalSystemSimulatorSessionsPostMultipleReader is a Reader for the ExternalSystemSimulatorSessionsPostMultiple structure.
type ExternalSystemSimulatorSessionsPostMultipleReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSimulatorSessionsPostMultipleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSimulatorSessionsPostMultipleOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/pel/public/externalsystemsimulatorSessions/PostMultiple] ExternalSystemSimulatorSessions_PostMultiple", response, response.Code())
	}
}

// NewExternalSystemSimulatorSessionsPostMultipleOK creates a ExternalSystemSimulatorSessionsPostMultipleOK with default headers values
func NewExternalSystemSimulatorSessionsPostMultipleOK(writer io.Writer) *ExternalSystemSimulatorSessionsPostMultipleOK {
	return &ExternalSystemSimulatorSessionsPostMultipleOK{

		Payload: writer,
	}
}

/*
ExternalSystemSimulatorSessionsPostMultipleOK describes a response with status code 200, with default header values.

ExternalSystemSimulatorSessionsPostMultipleOK external system simulator sessions post multiple o k
*/
type ExternalSystemSimulatorSessionsPostMultipleOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this external system simulator sessions post multiple o k response has a 2xx status code
func (o *ExternalSystemSimulatorSessionsPostMultipleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this external system simulator sessions post multiple o k response has a 3xx status code
func (o *ExternalSystemSimulatorSessionsPostMultipleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this external system simulator sessions post multiple o k response has a 4xx status code
func (o *ExternalSystemSimulatorSessionsPostMultipleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this external system simulator sessions post multiple o k response has a 5xx status code
func (o *ExternalSystemSimulatorSessionsPostMultipleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this external system simulator sessions post multiple o k response a status code equal to that given
func (o *ExternalSystemSimulatorSessionsPostMultipleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the external system simulator sessions post multiple o k response
func (o *ExternalSystemSimulatorSessionsPostMultipleOK) Code() int {
	return 200
}

func (o *ExternalSystemSimulatorSessionsPostMultipleOK) Error() string {
	return fmt.Sprintf("[POST /api/pel/public/externalsystemsimulatorSessions/PostMultiple][%d] externalSystemSimulatorSessionsPostMultipleOK", 200)
}

func (o *ExternalSystemSimulatorSessionsPostMultipleOK) String() string {
	return fmt.Sprintf("[POST /api/pel/public/externalsystemsimulatorSessions/PostMultiple][%d] externalSystemSimulatorSessionsPostMultipleOK", 200)
}

func (o *ExternalSystemSimulatorSessionsPostMultipleOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ExternalSystemSimulatorSessionsPostMultipleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
