// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemSimulatorSessionsPutReader is a Reader for the ExternalSystemSimulatorSessionsPut structure.
type ExternalSystemSimulatorSessionsPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSimulatorSessionsPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSimulatorSessionsPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExternalSystemSimulatorSessionsPutOK creates a ExternalSystemSimulatorSessionsPutOK with default headers values
func NewExternalSystemSimulatorSessionsPutOK() *ExternalSystemSimulatorSessionsPutOK {
	return &ExternalSystemSimulatorSessionsPutOK{}
}

/* ExternalSystemSimulatorSessionsPutOK describes a response with status code 200, with default header values.

ExternalSystemSimulatorSessionsPutOK external system simulator sessions put o k
*/
type ExternalSystemSimulatorSessionsPutOK struct {
	Payload *models.ExternalSystemSimulatorSessionOutput
}

func (o *ExternalSystemSimulatorSessionsPutOK) Error() string {
	return fmt.Sprintf("[PUT /api/pel/public/externalsystemsimulatorsessions/{id}][%d] externalSystemSimulatorSessionsPutOK  %+v", 200, o.Payload)
}
func (o *ExternalSystemSimulatorSessionsPutOK) GetPayload() *models.ExternalSystemSimulatorSessionOutput {
	return o.Payload
}

func (o *ExternalSystemSimulatorSessionsPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemSimulatorSessionOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
