// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemSimulatorSessionsGetReader is a Reader for the ExternalSystemSimulatorSessionsGet structure.
type ExternalSystemSimulatorSessionsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSimulatorSessionsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSimulatorSessionsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/pel/public/externalsystemsimulatorsessions/{id}] ExternalSystemSimulatorSessions_Get", response, response.Code())
	}
}

// NewExternalSystemSimulatorSessionsGetOK creates a ExternalSystemSimulatorSessionsGetOK with default headers values
func NewExternalSystemSimulatorSessionsGetOK() *ExternalSystemSimulatorSessionsGetOK {
	return &ExternalSystemSimulatorSessionsGetOK{}
}

/*
ExternalSystemSimulatorSessionsGetOK describes a response with status code 200, with default header values.

ExternalSystemSimulatorSessionsGetOK external system simulator sessions get o k
*/
type ExternalSystemSimulatorSessionsGetOK struct {
	Payload *models.ExternalSystemSimulatorSessionOutput
}

// IsSuccess returns true when this external system simulator sessions get o k response has a 2xx status code
func (o *ExternalSystemSimulatorSessionsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this external system simulator sessions get o k response has a 3xx status code
func (o *ExternalSystemSimulatorSessionsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this external system simulator sessions get o k response has a 4xx status code
func (o *ExternalSystemSimulatorSessionsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this external system simulator sessions get o k response has a 5xx status code
func (o *ExternalSystemSimulatorSessionsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this external system simulator sessions get o k response a status code equal to that given
func (o *ExternalSystemSimulatorSessionsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the external system simulator sessions get o k response
func (o *ExternalSystemSimulatorSessionsGetOK) Code() int {
	return 200
}

func (o *ExternalSystemSimulatorSessionsGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pel/public/externalsystemsimulatorsessions/{id}][%d] externalSystemSimulatorSessionsGetOK %s", 200, payload)
}

func (o *ExternalSystemSimulatorSessionsGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pel/public/externalsystemsimulatorsessions/{id}][%d] externalSystemSimulatorSessionsGetOK %s", 200, payload)
}

func (o *ExternalSystemSimulatorSessionsGetOK) GetPayload() *models.ExternalSystemSimulatorSessionOutput {
	return o.Payload
}

func (o *ExternalSystemSimulatorSessionsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemSimulatorSessionOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
