// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// NewExternalSystemSimulatorSessionsPostParams creates a new ExternalSystemSimulatorSessionsPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemSimulatorSessionsPostParams() *ExternalSystemSimulatorSessionsPostParams {
	return &ExternalSystemSimulatorSessionsPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemSimulatorSessionsPostParamsWithTimeout creates a new ExternalSystemSimulatorSessionsPostParams object
// with the ability to set a timeout on a request.
func NewExternalSystemSimulatorSessionsPostParamsWithTimeout(timeout time.Duration) *ExternalSystemSimulatorSessionsPostParams {
	return &ExternalSystemSimulatorSessionsPostParams{
		timeout: timeout,
	}
}

// NewExternalSystemSimulatorSessionsPostParamsWithContext creates a new ExternalSystemSimulatorSessionsPostParams object
// with the ability to set a context for a request.
func NewExternalSystemSimulatorSessionsPostParamsWithContext(ctx context.Context) *ExternalSystemSimulatorSessionsPostParams {
	return &ExternalSystemSimulatorSessionsPostParams{
		Context: ctx,
	}
}

// NewExternalSystemSimulatorSessionsPostParamsWithHTTPClient creates a new ExternalSystemSimulatorSessionsPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemSimulatorSessionsPostParamsWithHTTPClient(client *http.Client) *ExternalSystemSimulatorSessionsPostParams {
	return &ExternalSystemSimulatorSessionsPostParams{
		HTTPClient: client,
	}
}

/* ExternalSystemSimulatorSessionsPostParams contains all the parameters to send to the API endpoint
   for the external system simulator sessions post operation.

   Typically these are written to a http.Request.
*/
type ExternalSystemSimulatorSessionsPostParams struct {

	/* InputEntity.

	   SimulatorSession to be created
	*/
	InputEntity *models.ExternalSystemSimulatorSessionInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system simulator sessions post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSimulatorSessionsPostParams) WithDefaults() *ExternalSystemSimulatorSessionsPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system simulator sessions post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSimulatorSessionsPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system simulator sessions post params
func (o *ExternalSystemSimulatorSessionsPostParams) WithTimeout(timeout time.Duration) *ExternalSystemSimulatorSessionsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system simulator sessions post params
func (o *ExternalSystemSimulatorSessionsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system simulator sessions post params
func (o *ExternalSystemSimulatorSessionsPostParams) WithContext(ctx context.Context) *ExternalSystemSimulatorSessionsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system simulator sessions post params
func (o *ExternalSystemSimulatorSessionsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system simulator sessions post params
func (o *ExternalSystemSimulatorSessionsPostParams) WithHTTPClient(client *http.Client) *ExternalSystemSimulatorSessionsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system simulator sessions post params
func (o *ExternalSystemSimulatorSessionsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInputEntity adds the inputEntity to the external system simulator sessions post params
func (o *ExternalSystemSimulatorSessionsPostParams) WithInputEntity(inputEntity *models.ExternalSystemSimulatorSessionInput) *ExternalSystemSimulatorSessionsPostParams {
	o.SetInputEntity(inputEntity)
	return o
}

// SetInputEntity adds the inputEntity to the external system simulator sessions post params
func (o *ExternalSystemSimulatorSessionsPostParams) SetInputEntity(inputEntity *models.ExternalSystemSimulatorSessionInput) {
	o.InputEntity = inputEntity
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemSimulatorSessionsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.InputEntity != nil {
		if err := r.SetBodyParam(o.InputEntity); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
