// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemSimulatorSessionsPostReader is a Reader for the ExternalSystemSimulatorSessionsPost structure.
type ExternalSystemSimulatorSessionsPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSimulatorSessionsPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSimulatorSessionsPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/pel/public/externalsystemsimulatorsessions] ExternalSystemSimulatorSessions_Post", response, response.Code())
	}
}

// NewExternalSystemSimulatorSessionsPostOK creates a ExternalSystemSimulatorSessionsPostOK with default headers values
func NewExternalSystemSimulatorSessionsPostOK() *ExternalSystemSimulatorSessionsPostOK {
	return &ExternalSystemSimulatorSessionsPostOK{}
}

/*
ExternalSystemSimulatorSessionsPostOK describes a response with status code 200, with default header values.

ExternalSystemSimulatorSessionsPostOK external system simulator sessions post o k
*/
type ExternalSystemSimulatorSessionsPostOK struct {
	Payload *models.ExternalSystemSimulatorSessionOutput
}

// IsSuccess returns true when this external system simulator sessions post o k response has a 2xx status code
func (o *ExternalSystemSimulatorSessionsPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this external system simulator sessions post o k response has a 3xx status code
func (o *ExternalSystemSimulatorSessionsPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this external system simulator sessions post o k response has a 4xx status code
func (o *ExternalSystemSimulatorSessionsPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this external system simulator sessions post o k response has a 5xx status code
func (o *ExternalSystemSimulatorSessionsPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this external system simulator sessions post o k response a status code equal to that given
func (o *ExternalSystemSimulatorSessionsPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the external system simulator sessions post o k response
func (o *ExternalSystemSimulatorSessionsPostOK) Code() int {
	return 200
}

func (o *ExternalSystemSimulatorSessionsPostOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/pel/public/externalsystemsimulatorsessions][%d] externalSystemSimulatorSessionsPostOK %s", 200, payload)
}

func (o *ExternalSystemSimulatorSessionsPostOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/pel/public/externalsystemsimulatorsessions][%d] externalSystemSimulatorSessionsPostOK %s", 200, payload)
}

func (o *ExternalSystemSimulatorSessionsPostOK) GetPayload() *models.ExternalSystemSimulatorSessionOutput {
	return o.Payload
}

func (o *ExternalSystemSimulatorSessionsPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemSimulatorSessionOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
