// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// NewExternalSystemSimulatorSessionsPostMultipleParams creates a new ExternalSystemSimulatorSessionsPostMultipleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemSimulatorSessionsPostMultipleParams() *ExternalSystemSimulatorSessionsPostMultipleParams {
	return &ExternalSystemSimulatorSessionsPostMultipleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemSimulatorSessionsPostMultipleParamsWithTimeout creates a new ExternalSystemSimulatorSessionsPostMultipleParams object
// with the ability to set a timeout on a request.
func NewExternalSystemSimulatorSessionsPostMultipleParamsWithTimeout(timeout time.Duration) *ExternalSystemSimulatorSessionsPostMultipleParams {
	return &ExternalSystemSimulatorSessionsPostMultipleParams{
		timeout: timeout,
	}
}

// NewExternalSystemSimulatorSessionsPostMultipleParamsWithContext creates a new ExternalSystemSimulatorSessionsPostMultipleParams object
// with the ability to set a context for a request.
func NewExternalSystemSimulatorSessionsPostMultipleParamsWithContext(ctx context.Context) *ExternalSystemSimulatorSessionsPostMultipleParams {
	return &ExternalSystemSimulatorSessionsPostMultipleParams{
		Context: ctx,
	}
}

// NewExternalSystemSimulatorSessionsPostMultipleParamsWithHTTPClient creates a new ExternalSystemSimulatorSessionsPostMultipleParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemSimulatorSessionsPostMultipleParamsWithHTTPClient(client *http.Client) *ExternalSystemSimulatorSessionsPostMultipleParams {
	return &ExternalSystemSimulatorSessionsPostMultipleParams{
		HTTPClient: client,
	}
}

/* ExternalSystemSimulatorSessionsPostMultipleParams contains all the parameters to send to the API endpoint
   for the external system simulator sessions post multiple operation.

   Typically these are written to a http.Request.
*/
type ExternalSystemSimulatorSessionsPostMultipleParams struct {

	/* InputEntities.

	   Simulator sessions to be created
	*/
	InputEntities []*models.ExternalSystemSimulatorSessionInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system simulator sessions post multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) WithDefaults() *ExternalSystemSimulatorSessionsPostMultipleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system simulator sessions post multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system simulator sessions post multiple params
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) WithTimeout(timeout time.Duration) *ExternalSystemSimulatorSessionsPostMultipleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system simulator sessions post multiple params
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system simulator sessions post multiple params
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) WithContext(ctx context.Context) *ExternalSystemSimulatorSessionsPostMultipleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system simulator sessions post multiple params
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system simulator sessions post multiple params
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) WithHTTPClient(client *http.Client) *ExternalSystemSimulatorSessionsPostMultipleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system simulator sessions post multiple params
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInputEntities adds the inputEntities to the external system simulator sessions post multiple params
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) WithInputEntities(inputEntities []*models.ExternalSystemSimulatorSessionInput) *ExternalSystemSimulatorSessionsPostMultipleParams {
	o.SetInputEntities(inputEntities)
	return o
}

// SetInputEntities adds the inputEntities to the external system simulator sessions post multiple params
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) SetInputEntities(inputEntities []*models.ExternalSystemSimulatorSessionInput) {
	o.InputEntities = inputEntities
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemSimulatorSessionsPostMultipleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.InputEntities != nil {
		if err := r.SetBodyParam(o.InputEntities); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
