// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExternalSystemSimulatorSessionsGetParams creates a new ExternalSystemSimulatorSessionsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalSystemSimulatorSessionsGetParams() *ExternalSystemSimulatorSessionsGetParams {
	return &ExternalSystemSimulatorSessionsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalSystemSimulatorSessionsGetParamsWithTimeout creates a new ExternalSystemSimulatorSessionsGetParams object
// with the ability to set a timeout on a request.
func NewExternalSystemSimulatorSessionsGetParamsWithTimeout(timeout time.Duration) *ExternalSystemSimulatorSessionsGetParams {
	return &ExternalSystemSimulatorSessionsGetParams{
		timeout: timeout,
	}
}

// NewExternalSystemSimulatorSessionsGetParamsWithContext creates a new ExternalSystemSimulatorSessionsGetParams object
// with the ability to set a context for a request.
func NewExternalSystemSimulatorSessionsGetParamsWithContext(ctx context.Context) *ExternalSystemSimulatorSessionsGetParams {
	return &ExternalSystemSimulatorSessionsGetParams{
		Context: ctx,
	}
}

// NewExternalSystemSimulatorSessionsGetParamsWithHTTPClient creates a new ExternalSystemSimulatorSessionsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalSystemSimulatorSessionsGetParamsWithHTTPClient(client *http.Client) *ExternalSystemSimulatorSessionsGetParams {
	return &ExternalSystemSimulatorSessionsGetParams{
		HTTPClient: client,
	}
}

/* ExternalSystemSimulatorSessionsGetParams contains all the parameters to send to the API endpoint
   for the external system simulator sessions get operation.

   Typically these are written to a http.Request.
*/
type ExternalSystemSimulatorSessionsGetParams struct {

	/* ID.

	   The ExternalSystemUniqueID of the simulatorSession to retrieve
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external system simulator sessions get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSimulatorSessionsGetParams) WithDefaults() *ExternalSystemSimulatorSessionsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external system simulator sessions get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalSystemSimulatorSessionsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external system simulator sessions get params
func (o *ExternalSystemSimulatorSessionsGetParams) WithTimeout(timeout time.Duration) *ExternalSystemSimulatorSessionsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external system simulator sessions get params
func (o *ExternalSystemSimulatorSessionsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external system simulator sessions get params
func (o *ExternalSystemSimulatorSessionsGetParams) WithContext(ctx context.Context) *ExternalSystemSimulatorSessionsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external system simulator sessions get params
func (o *ExternalSystemSimulatorSessionsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external system simulator sessions get params
func (o *ExternalSystemSimulatorSessionsGetParams) WithHTTPClient(client *http.Client) *ExternalSystemSimulatorSessionsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external system simulator sessions get params
func (o *ExternalSystemSimulatorSessionsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the external system simulator sessions get params
func (o *ExternalSystemSimulatorSessionsGetParams) WithID(id string) *ExternalSystemSimulatorSessionsGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the external system simulator sessions get params
func (o *ExternalSystemSimulatorSessionsGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalSystemSimulatorSessionsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
