// Code generated by go-swagger; DO NOT EDIT.

package external_system_simulator_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemSimulatorSessionsPutReader is a Reader for the ExternalSystemSimulatorSessionsPut structure.
type ExternalSystemSimulatorSessionsPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemSimulatorSessionsPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemSimulatorSessionsPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/pel/public/externalsystemsimulatorsessions/{id}] ExternalSystemSimulatorSessions_Put", response, response.Code())
	}
}

// NewExternalSystemSimulatorSessionsPutOK creates a ExternalSystemSimulatorSessionsPutOK with default headers values
func NewExternalSystemSimulatorSessionsPutOK() *ExternalSystemSimulatorSessionsPutOK {
	return &ExternalSystemSimulatorSessionsPutOK{}
}

/*
ExternalSystemSimulatorSessionsPutOK describes a response with status code 200, with default header values.

ExternalSystemSimulatorSessionsPutOK external system simulator sessions put o k
*/
type ExternalSystemSimulatorSessionsPutOK struct {
	Payload *models.ExternalSystemSimulatorSessionOutput
}

// IsSuccess returns true when this external system simulator sessions put o k response has a 2xx status code
func (o *ExternalSystemSimulatorSessionsPutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this external system simulator sessions put o k response has a 3xx status code
func (o *ExternalSystemSimulatorSessionsPutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this external system simulator sessions put o k response has a 4xx status code
func (o *ExternalSystemSimulatorSessionsPutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this external system simulator sessions put o k response has a 5xx status code
func (o *ExternalSystemSimulatorSessionsPutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this external system simulator sessions put o k response a status code equal to that given
func (o *ExternalSystemSimulatorSessionsPutOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the external system simulator sessions put o k response
func (o *ExternalSystemSimulatorSessionsPutOK) Code() int {
	return 200
}

func (o *ExternalSystemSimulatorSessionsPutOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pel/public/externalsystemsimulatorsessions/{id}][%d] externalSystemSimulatorSessionsPutOK %s", 200, payload)
}

func (o *ExternalSystemSimulatorSessionsPutOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pel/public/externalsystemsimulatorsessions/{id}][%d] externalSystemSimulatorSessionsPutOK %s", 200, payload)
}

func (o *ExternalSystemSimulatorSessionsPutOK) GetPayload() *models.ExternalSystemSimulatorSessionOutput {
	return o.Payload
}

func (o *ExternalSystemSimulatorSessionsPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemSimulatorSessionOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
