// Code generated by go-swagger; DO NOT EDIT.

package external_system_activation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/odch/go-capzlog/models"
)

// ExternalSystemActivationPostReader is a Reader for the ExternalSystemActivationPost structure.
type ExternalSystemActivationPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalSystemActivationPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExternalSystemActivationPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExternalSystemActivationPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExternalSystemActivationPostOK creates a ExternalSystemActivationPostOK with default headers values
func NewExternalSystemActivationPostOK() *ExternalSystemActivationPostOK {
	return &ExternalSystemActivationPostOK{}
}

/* ExternalSystemActivationPostOK describes a response with status code 200, with default header values.

ExternalSystemActivationPostOK external system activation post o k
*/
type ExternalSystemActivationPostOK struct {
	Payload *models.ExternalSystemConnectionActivationOutput
}

func (o *ExternalSystemActivationPostOK) Error() string {
	return fmt.Sprintf("[POST /api/pel/public/externalsystemactivation][%d] externalSystemActivationPostOK  %+v", 200, o.Payload)
}
func (o *ExternalSystemActivationPostOK) GetPayload() *models.ExternalSystemConnectionActivationOutput {
	return o.Payload
}

func (o *ExternalSystemActivationPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalSystemConnectionActivationOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExternalSystemActivationPostBadRequest creates a ExternalSystemActivationPostBadRequest with default headers values
func NewExternalSystemActivationPostBadRequest() *ExternalSystemActivationPostBadRequest {
	return &ExternalSystemActivationPostBadRequest{}
}

/* ExternalSystemActivationPostBadRequest describes a response with status code 400, with default header values.

ExternalSystemActivationPostBadRequest external system activation post bad request
*/
type ExternalSystemActivationPostBadRequest struct {
	Payload string
}

func (o *ExternalSystemActivationPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/pel/public/externalsystemactivation][%d] externalSystemActivationPostBadRequest  %+v", 400, o.Payload)
}
func (o *ExternalSystemActivationPostBadRequest) GetPayload() string {
	return o.Payload
}

func (o *ExternalSystemActivationPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
