// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExternalSystemConnectionActivationOutput external system connection activation output
//
// swagger:model ExternalSystemConnectionActivationOutput
type ExternalSystemConnectionActivationOutput struct {
	ExternalSystemConnectionActivationBase

	ExternalSystemConnectionActivationOutputAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ExternalSystemConnectionActivationOutput) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ExternalSystemConnectionActivationBase
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ExternalSystemConnectionActivationBase = aO0

	// AO1
	var aO1 ExternalSystemConnectionActivationOutputAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.ExternalSystemConnectionActivationOutputAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ExternalSystemConnectionActivationOutput) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.ExternalSystemConnectionActivationBase)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.ExternalSystemConnectionActivationOutputAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this external system connection activation output
func (m *ExternalSystemConnectionActivationOutput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this external system connection activation output based on context it is used
func (m *ExternalSystemConnectionActivationOutput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExternalSystemConnectionActivationOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExternalSystemConnectionActivationOutput) UnmarshalBinary(b []byte) error {
	var res ExternalSystemConnectionActivationOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ExternalSystemConnectionActivationOutputAllOf1 external system connection activation output all of1
//
// swagger:model ExternalSystemConnectionActivationOutputAllOf1
type ExternalSystemConnectionActivationOutputAllOf1 interface{}
