// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SimulatorOutput simulator output
//
// swagger:model SimulatorOutput
type SimulatorOutput struct {

	// authorization number
	// Required: true
	// Min Length: 1
	AuthorizationNumber *string `json:"AuthorizationNumber"`

	// flight simulation training device type
	FlightSimulationTrainingDeviceType FlightSimulationTrainingDeviceTypes `json:"FlightSimulationTrainingDeviceType,omitempty"`

	// i c a o designator
	// Required: true
	// Min Length: 1
	ICAODesignator *string `json:"ICAODesignator"`

	// level
	Level string `json:"Level,omitempty"`

	// The variant of the simulator, in case several variants are available for the provided registration in capzlog.aero. If no variant is specified and there are multiple variants for the provided registration in capzlog.aero, one is selected randomly
	Variant string `json:"Variant,omitempty"`
}

// Validate validates this simulator output
func (m *SimulatorOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthorizationNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFlightSimulationTrainingDeviceType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateICAODesignator(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SimulatorOutput) validateAuthorizationNumber(formats strfmt.Registry) error {

	if err := validate.Required("AuthorizationNumber", "body", m.AuthorizationNumber); err != nil {
		return err
	}

	if err := validate.MinLength("AuthorizationNumber", "body", *m.AuthorizationNumber, 1); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorOutput) validateFlightSimulationTrainingDeviceType(formats strfmt.Registry) error {
	if swag.IsZero(m.FlightSimulationTrainingDeviceType) { // not required
		return nil
	}

	if err := m.FlightSimulationTrainingDeviceType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("FlightSimulationTrainingDeviceType")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("FlightSimulationTrainingDeviceType")
		}
		return err
	}

	return nil
}

func (m *SimulatorOutput) validateICAODesignator(formats strfmt.Registry) error {

	if err := validate.Required("ICAODesignator", "body", m.ICAODesignator); err != nil {
		return err
	}

	if err := validate.MinLength("ICAODesignator", "body", *m.ICAODesignator, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this simulator output based on the context it is used
func (m *SimulatorOutput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFlightSimulationTrainingDeviceType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SimulatorOutput) contextValidateFlightSimulationTrainingDeviceType(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.FlightSimulationTrainingDeviceType) { // not required
		return nil
	}

	if err := m.FlightSimulationTrainingDeviceType.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("FlightSimulationTrainingDeviceType")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("FlightSimulationTrainingDeviceType")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SimulatorOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SimulatorOutput) UnmarshalBinary(b []byte) error {
	var res SimulatorOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
