// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SimulatorSessionOutputBase Represents a simulator session in capzlog.aero
//
// swagger:model SimulatorSessionOutputBase
type SimulatorSessionOutputBase struct {

	// date
	// Required: true
	// Min Length: 1
	// Pattern: ^\d{4}\-(0[1-9]|1[0-2])\-(0[1-9]|[1-2][0-9]|3[0-1])$
	// Format: date-time
	Date *strfmt.DateTime `json:"Date"`

	// day landings
	// Required: true
	// Maximum: 100
	// Minimum: 0
	DayLandings *int32 `json:"DayLandings"`

	// day takeoffs
	// Required: true
	// Maximum: 100
	// Minimum: 0
	DayTakeoffs *int32 `json:"DayTakeoffs"`

	// landings
	// Required: true
	// Maximum: 100
	// Minimum: 0
	Landings *int32 `json:"Landings"`

	// markers
	Markers []*Marker `json:"Markers"`

	// multi engine time
	// Required: true
	// Min Length: 1
	// Pattern: ^\d{1-5}:[0-5][0-9]$
	// Format: duration
	MultiEngineTime *strfmt.Duration `json:"MultiEngineTime"`

	// night landings
	// Required: true
	// Maximum: 100
	// Minimum: 0
	NightLandings *int32 `json:"NightLandings"`

	// night takeoffs
	// Required: true
	// Maximum: 100
	// Minimum: 0
	NightTakeoffs *int32 `json:"NightTakeoffs"`

	// pilot function
	// Required: true
	PilotFunction *PilotFunctions `json:"PilotFunction"`

	// remark
	Remark string `json:"Remark,omitempty"`

	// session time
	// Required: true
	// Min Length: 1
	// Pattern: ^\d{1-5}:[0-5][0-9]$
	// Format: duration
	SessionTime *strfmt.Duration `json:"SessionTime"`

	// sfi sfe time
	// Required: true
	// Min Length: 1
	// Pattern: ^\d{1-5}:[0-5][0-9]$
	// Format: duration
	SfiSfeTime *strfmt.Duration `json:"SfiSfeTime"`

	// simulator
	Simulator *SimulatorOutput `json:"Simulator,omitempty"`

	// single engine time
	// Required: true
	// Min Length: 1
	// Pattern: ^\d{1-5}:[0-5][0-9]$
	// Format: duration
	SingleEngineTime *strfmt.Duration `json:"SingleEngineTime"`

	// status
	// Required: true
	Status *UpdateStatus `json:"Status"`

	// takeoffs
	// Required: true
	// Maximum: 100
	// Minimum: 0
	Takeoffs *int32 `json:"Takeoffs"`

	// trainee time
	// Required: true
	// Min Length: 1
	// Pattern: ^\d{1-5}:[0-5][0-9]$
	// Format: duration
	TraineeTime *strfmt.Duration `json:"TraineeTime"`
}

// Validate validates this simulator session output base
func (m *SimulatorSessionOutputBase) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDayLandings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDayTakeoffs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLandings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMarkers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMultiEngineTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNightLandings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNightTakeoffs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePilotFunction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSfiSfeTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSimulator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSingleEngineTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTakeoffs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTraineeTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SimulatorSessionOutputBase) validateDate(formats strfmt.Registry) error {

	if err := validate.Required("Date", "body", m.Date); err != nil {
		return err
	}

	if err := validate.MinLength("Date", "body", m.Date.String(), 1); err != nil {
		return err
	}

	if err := validate.Pattern("Date", "body", m.Date.String(), `^\d{4}\-(0[1-9]|1[0-2])\-(0[1-9]|[1-2][0-9]|3[0-1])$`); err != nil {
		return err
	}

	if err := validate.FormatOf("Date", "body", "date-time", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateDayLandings(formats strfmt.Registry) error {

	if err := validate.Required("DayLandings", "body", m.DayLandings); err != nil {
		return err
	}

	if err := validate.MinimumInt("DayLandings", "body", int64(*m.DayLandings), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("DayLandings", "body", int64(*m.DayLandings), 100, false); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateDayTakeoffs(formats strfmt.Registry) error {

	if err := validate.Required("DayTakeoffs", "body", m.DayTakeoffs); err != nil {
		return err
	}

	if err := validate.MinimumInt("DayTakeoffs", "body", int64(*m.DayTakeoffs), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("DayTakeoffs", "body", int64(*m.DayTakeoffs), 100, false); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateLandings(formats strfmt.Registry) error {

	if err := validate.Required("Landings", "body", m.Landings); err != nil {
		return err
	}

	if err := validate.MinimumInt("Landings", "body", int64(*m.Landings), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("Landings", "body", int64(*m.Landings), 100, false); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateMarkers(formats strfmt.Registry) error {
	if swag.IsZero(m.Markers) { // not required
		return nil
	}

	for i := 0; i < len(m.Markers); i++ {
		if swag.IsZero(m.Markers[i]) { // not required
			continue
		}

		if m.Markers[i] != nil {
			if err := m.Markers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Markers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Markers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateMultiEngineTime(formats strfmt.Registry) error {

	if err := validate.Required("MultiEngineTime", "body", m.MultiEngineTime); err != nil {
		return err
	}

	if err := validate.MinLength("MultiEngineTime", "body", m.MultiEngineTime.String(), 1); err != nil {
		return err
	}

	if err := validate.Pattern("MultiEngineTime", "body", m.MultiEngineTime.String(), `^\d{1-5}:[0-5][0-9]$`); err != nil {
		return err
	}

	if err := validate.FormatOf("MultiEngineTime", "body", "duration", m.MultiEngineTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateNightLandings(formats strfmt.Registry) error {

	if err := validate.Required("NightLandings", "body", m.NightLandings); err != nil {
		return err
	}

	if err := validate.MinimumInt("NightLandings", "body", int64(*m.NightLandings), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("NightLandings", "body", int64(*m.NightLandings), 100, false); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateNightTakeoffs(formats strfmt.Registry) error {

	if err := validate.Required("NightTakeoffs", "body", m.NightTakeoffs); err != nil {
		return err
	}

	if err := validate.MinimumInt("NightTakeoffs", "body", int64(*m.NightTakeoffs), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("NightTakeoffs", "body", int64(*m.NightTakeoffs), 100, false); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validatePilotFunction(formats strfmt.Registry) error {

	if err := validate.Required("PilotFunction", "body", m.PilotFunction); err != nil {
		return err
	}

	if err := validate.Required("PilotFunction", "body", m.PilotFunction); err != nil {
		return err
	}

	if m.PilotFunction != nil {
		if err := m.PilotFunction.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("PilotFunction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("PilotFunction")
			}
			return err
		}
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateSessionTime(formats strfmt.Registry) error {

	if err := validate.Required("SessionTime", "body", m.SessionTime); err != nil {
		return err
	}

	if err := validate.MinLength("SessionTime", "body", m.SessionTime.String(), 1); err != nil {
		return err
	}

	if err := validate.Pattern("SessionTime", "body", m.SessionTime.String(), `^\d{1-5}:[0-5][0-9]$`); err != nil {
		return err
	}

	if err := validate.FormatOf("SessionTime", "body", "duration", m.SessionTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateSfiSfeTime(formats strfmt.Registry) error {

	if err := validate.Required("SfiSfeTime", "body", m.SfiSfeTime); err != nil {
		return err
	}

	if err := validate.MinLength("SfiSfeTime", "body", m.SfiSfeTime.String(), 1); err != nil {
		return err
	}

	if err := validate.Pattern("SfiSfeTime", "body", m.SfiSfeTime.String(), `^\d{1-5}:[0-5][0-9]$`); err != nil {
		return err
	}

	if err := validate.FormatOf("SfiSfeTime", "body", "duration", m.SfiSfeTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateSimulator(formats strfmt.Registry) error {
	if swag.IsZero(m.Simulator) { // not required
		return nil
	}

	if m.Simulator != nil {
		if err := m.Simulator.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Simulator")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Simulator")
			}
			return err
		}
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateSingleEngineTime(formats strfmt.Registry) error {

	if err := validate.Required("SingleEngineTime", "body", m.SingleEngineTime); err != nil {
		return err
	}

	if err := validate.MinLength("SingleEngineTime", "body", m.SingleEngineTime.String(), 1); err != nil {
		return err
	}

	if err := validate.Pattern("SingleEngineTime", "body", m.SingleEngineTime.String(), `^\d{1-5}:[0-5][0-9]$`); err != nil {
		return err
	}

	if err := validate.FormatOf("SingleEngineTime", "body", "duration", m.SingleEngineTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("Status", "body", m.Status); err != nil {
		return err
	}

	if err := validate.Required("Status", "body", m.Status); err != nil {
		return err
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Status")
			}
			return err
		}
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateTakeoffs(formats strfmt.Registry) error {

	if err := validate.Required("Takeoffs", "body", m.Takeoffs); err != nil {
		return err
	}

	if err := validate.MinimumInt("Takeoffs", "body", int64(*m.Takeoffs), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("Takeoffs", "body", int64(*m.Takeoffs), 100, false); err != nil {
		return err
	}

	return nil
}

func (m *SimulatorSessionOutputBase) validateTraineeTime(formats strfmt.Registry) error {

	if err := validate.Required("TraineeTime", "body", m.TraineeTime); err != nil {
		return err
	}

	if err := validate.MinLength("TraineeTime", "body", m.TraineeTime.String(), 1); err != nil {
		return err
	}

	if err := validate.Pattern("TraineeTime", "body", m.TraineeTime.String(), `^\d{1-5}:[0-5][0-9]$`); err != nil {
		return err
	}

	if err := validate.FormatOf("TraineeTime", "body", "duration", m.TraineeTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this simulator session output base based on the context it is used
func (m *SimulatorSessionOutputBase) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMarkers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePilotFunction(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSimulator(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SimulatorSessionOutputBase) contextValidateMarkers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Markers); i++ {

		if m.Markers[i] != nil {
			if err := m.Markers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Markers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Markers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SimulatorSessionOutputBase) contextValidatePilotFunction(ctx context.Context, formats strfmt.Registry) error {

	if m.PilotFunction != nil {
		if err := m.PilotFunction.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("PilotFunction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("PilotFunction")
			}
			return err
		}
	}

	return nil
}

func (m *SimulatorSessionOutputBase) contextValidateSimulator(ctx context.Context, formats strfmt.Registry) error {

	if m.Simulator != nil {
		if err := m.Simulator.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Simulator")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Simulator")
			}
			return err
		}
	}

	return nil
}

func (m *SimulatorSessionOutputBase) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {
		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SimulatorSessionOutputBase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SimulatorSessionOutputBase) UnmarshalBinary(b []byte) error {
	var res SimulatorSessionOutputBase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
